export default {
    BOARD_WIDTH: 20,
    BOARD_HEIGHT: 30,
    BLOCK_SIZE: 25,
    SHAPE_SIZE: 4,
    LEVEL_UP_AT_LINE: 5,

    UI_OFFSET: 50,
    UI_OFFSET_X: 50,
    UI_OFFSET_Y: 50,
    RENDER_OFFSET: 0,
}